### PR TITLE
very minor change to intro

### PR DESCRIPTION
**Pull request by deesto**
I'm fairly certain 'Clubbering' isn't a word -- yet. ;)

### CODE REVIEW

**Comment by gforcada** [comment]
@deesto no, most probably not, that's our automated bots, sorry.

@thet @frapell @fulv @pbauer would you mind merging?

**Comment by deesto** [comment]
Thank you. I now have the ability to merge this myself, but that would be bad form ... can someone else please merge it?

**Comment by gforcada** [comment]
@deesto welcome to Plone! I'm merging it myself.

**Comment by deesto** [comment]
Many thanks, @gforcada.

**Pull request merged**
